######################################################################
# Automatically generated by qmake (3.0) ?? 8? 28 15:44:22 2017
######################################################################

TEMPLATE = app
TARGET = datagenerate
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++11
CONFIG += debug

# Input
SOURCES += main.cpp
