#############################################################################
# Makefile for building: datagenerate
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  datagenerate.pro
# Template: app
# Command: /home/wj/anaconda3/bin/qmake -o Makefile datagenerate.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/home/wj/anaconda3/include/qt -I/home/wj/anaconda3/include/qt/QtWidgets -I/home/wj/anaconda3/include/qt/QtGui -I/home/wj/anaconda3/include/qt/QtCore -I. -I/home/wj/anaconda3/mkspecs/linux-g++
QMAKE         = /home/wj/anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/wj/anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/wj/anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = datagenerate1.0.0
DISTDIR = /1_data/wj/work/mnistgeood_data_generate/.tmp/datagenerate1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/wj/anaconda3/lib
LIBS          = $(SUBLIBS) -L/home/wj/anaconda3/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /home/wj/anaconda3/mkspecs/features/spec_pre.prf \
		/home/wj/anaconda3/mkspecs/common/unix.conf \
		/home/wj/anaconda3/mkspecs/common/linux.conf \
		/home/wj/anaconda3/mkspecs/common/sanitize.conf \
		/home/wj/anaconda3/mkspecs/common/gcc-base.conf \
		/home/wj/anaconda3/mkspecs/common/gcc-base-unix.conf \
		/home/wj/anaconda3/mkspecs/common/g++-base.conf \
		/home/wj/anaconda3/mkspecs/common/g++-unix.conf \
		/home/wj/anaconda3/mkspecs/qconfig.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_location.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/wj/anaconda3/mkspecs/features/qt_functions.prf \
		/home/wj/anaconda3/mkspecs/features/qt_config.prf \
		/home/wj/anaconda3/mkspecs/linux-g++/qmake.conf \
		/home/wj/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/wj/anaconda3/mkspecs/features/exclusive_builds.prf \
		/home/wj/anaconda3/mkspecs/features/toolchain.prf \
		/home/wj/anaconda3/mkspecs/features/default_pre.prf \
		/home/wj/anaconda3/mkspecs/features/resolve_config.prf \
		/home/wj/anaconda3/mkspecs/features/default_post.prf \
		/home/wj/anaconda3/mkspecs/features/warn_on.prf \
		/home/wj/anaconda3/mkspecs/features/qt.prf \
		/home/wj/anaconda3/mkspecs/features/resources.prf \
		/home/wj/anaconda3/mkspecs/features/moc.prf \
		/home/wj/anaconda3/mkspecs/features/unix/opengl.prf \
		/home/wj/anaconda3/mkspecs/features/uic.prf \
		/home/wj/anaconda3/mkspecs/features/unix/thread.prf \
		/home/wj/anaconda3/mkspecs/features/qmake_use.prf \
		/home/wj/anaconda3/mkspecs/features/file_copies.prf \
		/home/wj/anaconda3/mkspecs/features/testcase_targets.prf \
		/home/wj/anaconda3/mkspecs/features/exceptions.prf \
		/home/wj/anaconda3/mkspecs/features/yacc.prf \
		/home/wj/anaconda3/mkspecs/features/lex.prf \
		datagenerate.pro  main.cpp
QMAKE_TARGET  = datagenerate
DESTDIR       = 
TARGET        = datagenerate


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: datagenerate.pro /home/wj/anaconda3/mkspecs/linux-g++/qmake.conf /home/wj/anaconda3/mkspecs/features/spec_pre.prf \
		/home/wj/anaconda3/mkspecs/common/unix.conf \
		/home/wj/anaconda3/mkspecs/common/linux.conf \
		/home/wj/anaconda3/mkspecs/common/sanitize.conf \
		/home/wj/anaconda3/mkspecs/common/gcc-base.conf \
		/home/wj/anaconda3/mkspecs/common/gcc-base-unix.conf \
		/home/wj/anaconda3/mkspecs/common/g++-base.conf \
		/home/wj/anaconda3/mkspecs/common/g++-unix.conf \
		/home/wj/anaconda3/mkspecs/qconfig.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_location.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/wj/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/wj/anaconda3/mkspecs/features/qt_functions.prf \
		/home/wj/anaconda3/mkspecs/features/qt_config.prf \
		/home/wj/anaconda3/mkspecs/linux-g++/qmake.conf \
		/home/wj/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/wj/anaconda3/mkspecs/features/exclusive_builds.prf \
		/home/wj/anaconda3/mkspecs/features/toolchain.prf \
		/home/wj/anaconda3/mkspecs/features/default_pre.prf \
		/home/wj/anaconda3/mkspecs/features/resolve_config.prf \
		/home/wj/anaconda3/mkspecs/features/default_post.prf \
		/home/wj/anaconda3/mkspecs/features/warn_on.prf \
		/home/wj/anaconda3/mkspecs/features/qt.prf \
		/home/wj/anaconda3/mkspecs/features/resources.prf \
		/home/wj/anaconda3/mkspecs/features/moc.prf \
		/home/wj/anaconda3/mkspecs/features/unix/opengl.prf \
		/home/wj/anaconda3/mkspecs/features/uic.prf \
		/home/wj/anaconda3/mkspecs/features/unix/thread.prf \
		/home/wj/anaconda3/mkspecs/features/qmake_use.prf \
		/home/wj/anaconda3/mkspecs/features/file_copies.prf \
		/home/wj/anaconda3/mkspecs/features/testcase_targets.prf \
		/home/wj/anaconda3/mkspecs/features/exceptions.prf \
		/home/wj/anaconda3/mkspecs/features/yacc.prf \
		/home/wj/anaconda3/mkspecs/features/lex.prf \
		datagenerate.pro \
		/home/wj/anaconda3/lib/libQt5Widgets.prl \
		/home/wj/anaconda3/lib/libQt5Gui.prl \
		/home/wj/anaconda3/lib/libQt5Core.prl
	$(QMAKE) -o Makefile datagenerate.pro
/home/wj/anaconda3/mkspecs/features/spec_pre.prf:
/home/wj/anaconda3/mkspecs/common/unix.conf:
/home/wj/anaconda3/mkspecs/common/linux.conf:
/home/wj/anaconda3/mkspecs/common/sanitize.conf:
/home/wj/anaconda3/mkspecs/common/gcc-base.conf:
/home/wj/anaconda3/mkspecs/common/gcc-base-unix.conf:
/home/wj/anaconda3/mkspecs/common/g++-base.conf:
/home/wj/anaconda3/mkspecs/common/g++-unix.conf:
/home/wj/anaconda3/mkspecs/qconfig.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3drender.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_charts.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_core.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_core_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_dbus.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_designer.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_gui.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_help.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_help_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_input_support_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_location.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_location_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_network.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_network_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_nfc.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_opengl.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_positioning.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_qml.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_quick.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_repparser.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_script.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_script_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_scxml.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_sensors.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_serialport.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_service_support_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_sql.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_svg.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_testlib.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_uitools.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_webengine.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_websockets.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_webview.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_widgets.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_x11extras.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_xml.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/wj/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/wj/anaconda3/mkspecs/features/qt_functions.prf:
/home/wj/anaconda3/mkspecs/features/qt_config.prf:
/home/wj/anaconda3/mkspecs/linux-g++/qmake.conf:
/home/wj/anaconda3/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/wj/anaconda3/mkspecs/features/exclusive_builds.prf:
/home/wj/anaconda3/mkspecs/features/toolchain.prf:
/home/wj/anaconda3/mkspecs/features/default_pre.prf:
/home/wj/anaconda3/mkspecs/features/resolve_config.prf:
/home/wj/anaconda3/mkspecs/features/default_post.prf:
/home/wj/anaconda3/mkspecs/features/warn_on.prf:
/home/wj/anaconda3/mkspecs/features/qt.prf:
/home/wj/anaconda3/mkspecs/features/resources.prf:
/home/wj/anaconda3/mkspecs/features/moc.prf:
/home/wj/anaconda3/mkspecs/features/unix/opengl.prf:
/home/wj/anaconda3/mkspecs/features/uic.prf:
/home/wj/anaconda3/mkspecs/features/unix/thread.prf:
/home/wj/anaconda3/mkspecs/features/qmake_use.prf:
/home/wj/anaconda3/mkspecs/features/file_copies.prf:
/home/wj/anaconda3/mkspecs/features/testcase_targets.prf:
/home/wj/anaconda3/mkspecs/features/exceptions.prf:
/home/wj/anaconda3/mkspecs/features/yacc.prf:
/home/wj/anaconda3/mkspecs/features/lex.prf:
datagenerate.pro:
/home/wj/anaconda3/lib/libQt5Widgets.prl:
/home/wj/anaconda3/lib/libQt5Gui.prl:
/home/wj/anaconda3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile datagenerate.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /home/wj/anaconda3/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/wj/anaconda3/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++11 -g -Wall -W -dM -E -o moc_predefs.h /home/wj/anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp /home/wj/anaconda3/include/qt/QtCore/QtCore \
		/home/wj/anaconda3/include/qt/QtCore/QtCoreDepends \
		/home/wj/anaconda3/include/qt/QtCore/qglobal.h \
		/home/wj/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/home/wj/anaconda3/include/qt/QtCore/qconfig.h \
		/home/wj/anaconda3/include/qt/QtCore/qtcore-config.h \
		/home/wj/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/home/wj/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/home/wj/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/home/wj/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/home/wj/anaconda3/include/qt/QtCore/qsysinfo.h \
		/home/wj/anaconda3/include/qt/QtCore/qlogging.h \
		/home/wj/anaconda3/include/qt/QtCore/qflags.h \
		/home/wj/anaconda3/include/qt/QtCore/qatomic.h \
		/home/wj/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/home/wj/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/home/wj/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/home/wj/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/home/wj/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/home/wj/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/home/wj/anaconda3/include/qt/QtCore/qmutex.h \
		/home/wj/anaconda3/include/qt/QtCore/qnumeric.h \
		/home/wj/anaconda3/include/qt/QtCore/qversiontagging.h \
		/home/wj/anaconda3/include/qt/QtCore/qabstractanimation.h \
		/home/wj/anaconda3/include/qt/QtCore/qobject.h \
		/home/wj/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/home/wj/anaconda3/include/qt/QtCore/qnamespace.h \
		/home/wj/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/home/wj/anaconda3/include/qt/QtCore/qstring.h \
		/home/wj/anaconda3/include/qt/QtCore/qchar.h \
		/home/wj/anaconda3/include/qt/QtCore/qbytearray.h \
		/home/wj/anaconda3/include/qt/QtCore/qrefcount.h \
		/home/wj/anaconda3/include/qt/QtCore/qarraydata.h \
		/home/wj/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/home/wj/anaconda3/include/qt/QtCore/qlist.h \
		/home/wj/anaconda3/include/qt/QtCore/qalgorithms.h \
		/home/wj/anaconda3/include/qt/QtCore/qiterator.h \
		/home/wj/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/home/wj/anaconda3/include/qt/QtCore/qpair.h \
		/home/wj/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/home/wj/anaconda3/include/qt/QtCore/qstringlist.h \
		/home/wj/anaconda3/include/qt/QtCore/qregexp.h \
		/home/wj/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/home/wj/anaconda3/include/qt/QtCore/qcoreevent.h \
		/home/wj/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/home/wj/anaconda3/include/qt/QtCore/qmetatype.h \
		/home/wj/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/home/wj/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/home/wj/anaconda3/include/qt/QtCore/qobject_impl.h \
		/home/wj/anaconda3/include/qt/QtCore/qabstracteventdispatcher.h \
		/home/wj/anaconda3/include/qt/QtCore/qeventloop.h \
		/home/wj/anaconda3/include/qt/QtCore/qabstractitemmodel.h \
		/home/wj/anaconda3/include/qt/QtCore/qvariant.h \
		/home/wj/anaconda3/include/qt/QtCore/qmap.h \
		/home/wj/anaconda3/include/qt/QtCore/qdebug.h \
		/home/wj/anaconda3/include/qt/QtCore/qhash.h \
		/home/wj/anaconda3/include/qt/QtCore/qtextstream.h \
		/home/wj/anaconda3/include/qt/QtCore/qiodevice.h \
		/home/wj/anaconda3/include/qt/QtCore/qlocale.h \
		/home/wj/anaconda3/include/qt/QtCore/qshareddata.h \
		/home/wj/anaconda3/include/qt/QtCore/qvector.h \
		/home/wj/anaconda3/include/qt/QtCore/qpoint.h \
		/home/wj/anaconda3/include/qt/QtCore/qset.h \
		/home/wj/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/home/wj/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/home/wj/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/home/wj/anaconda3/include/qt/QtCore/qabstractnativeeventfilter.h \
		/home/wj/anaconda3/include/qt/QtCore/qabstractproxymodel.h \
		/home/wj/anaconda3/include/qt/QtCore/qabstractstate.h \
		/home/wj/anaconda3/include/qt/QtCore/qabstracttransition.h \
		/home/wj/anaconda3/include/qt/QtCore/qanimationgroup.h \
		/home/wj/anaconda3/include/qt/QtCore/qarraydataops.h \
		/home/wj/anaconda3/include/qt/QtCore/qarraydatapointer.h \
		/home/wj/anaconda3/include/qt/QtCore/qbasictimer.h \
		/home/wj/anaconda3/include/qt/QtCore/qbitarray.h \
		/home/wj/anaconda3/include/qt/QtCore/qbuffer.h \
		/home/wj/anaconda3/include/qt/QtCore/qbytearraymatcher.h \
		/home/wj/anaconda3/include/qt/QtCore/qcache.h \
		/home/wj/anaconda3/include/qt/QtCore/qcollator.h \
		/home/wj/anaconda3/include/qt/QtCore/qcommandlineoption.h \
		/home/wj/anaconda3/include/qt/QtCore/qcommandlineparser.h \
		/home/wj/anaconda3/include/qt/QtCore/qcoreapplication.h \
		/home/wj/anaconda3/include/qt/QtCore/qcryptographichash.h \
		/home/wj/anaconda3/include/qt/QtCore/qdatastream.h \
		/home/wj/anaconda3/include/qt/QtCore/qdatetime.h \
		/home/wj/anaconda3/include/qt/QtCore/qdeadlinetimer.h \
		/home/wj/anaconda3/include/qt/QtCore/qelapsedtimer.h \
		/home/wj/anaconda3/include/qt/QtCore/qdir.h \
		/home/wj/anaconda3/include/qt/QtCore/qfileinfo.h \
		/home/wj/anaconda3/include/qt/QtCore/qfile.h \
		/home/wj/anaconda3/include/qt/QtCore/qfiledevice.h \
		/home/wj/anaconda3/include/qt/QtCore/qdiriterator.h \
		/home/wj/anaconda3/include/qt/QtCore/qeasingcurve.h \
		/home/wj/anaconda3/include/qt/QtCore/qendian.h \
		/home/wj/anaconda3/include/qt/QtCore/qeventtransition.h \
		/home/wj/anaconda3/include/qt/QtCore/qexception.h \
		/home/wj/anaconda3/include/qt/QtCore/qfactoryinterface.h \
		/home/wj/anaconda3/include/qt/QtCore/qfileselector.h \
		/home/wj/anaconda3/include/qt/QtCore/QObject \
		/home/wj/anaconda3/include/qt/QtCore/QStringList \
		/home/wj/anaconda3/include/qt/QtCore/qfilesystemwatcher.h \
		/home/wj/anaconda3/include/qt/QtCore/qfinalstate.h \
		/home/wj/anaconda3/include/qt/QtCore/qfuture.h \
		/home/wj/anaconda3/include/qt/QtCore/qfutureinterface.h \
		/home/wj/anaconda3/include/qt/QtCore/qrunnable.h \
		/home/wj/anaconda3/include/qt/QtCore/qresultstore.h \
		/home/wj/anaconda3/include/qt/QtCore/qfuturesynchronizer.h \
		/home/wj/anaconda3/include/qt/QtCore/qfuturewatcher.h \
		/home/wj/anaconda3/include/qt/QtCore/qhistorystate.h \
		/home/wj/anaconda3/include/qt/QtCore/qidentityproxymodel.h \
		/home/wj/anaconda3/include/qt/QtCore/qisenum.h \
		/home/wj/anaconda3/include/qt/QtCore/qitemselectionmodel.h \
		/home/wj/anaconda3/include/qt/QtCore/qjsonarray.h \
		/home/wj/anaconda3/include/qt/QtCore/qjsonvalue.h \
		/home/wj/anaconda3/include/qt/QtCore/qjsondocument.h \
		/home/wj/anaconda3/include/qt/QtCore/qjsonobject.h \
		/home/wj/anaconda3/include/qt/QtCore/qlibrary.h \
		/home/wj/anaconda3/include/qt/QtCore/qlibraryinfo.h \
		/home/wj/anaconda3/include/qt/QtCore/qversionnumber.h \
		/home/wj/anaconda3/include/qt/QtCore/qline.h \
		/home/wj/anaconda3/include/qt/QtCore/qlinkedlist.h \
		/home/wj/anaconda3/include/qt/QtCore/qlockfile.h \
		/home/wj/anaconda3/include/qt/QtCore/qloggingcategory.h \
		/home/wj/anaconda3/include/qt/QtCore/qmargins.h \
		/home/wj/anaconda3/include/qt/QtCore/qmath.h \
		/home/wj/anaconda3/include/qt/QtCore/qmessageauthenticationcode.h \
		/home/wj/anaconda3/include/qt/QtCore/qmetaobject.h \
		/home/wj/anaconda3/include/qt/QtCore/qmimedata.h \
		/home/wj/anaconda3/include/qt/QtCore/qmimedatabase.h \
		/home/wj/anaconda3/include/qt/QtCore/qmimetype.h \
		/home/wj/anaconda3/include/qt/QtCore/qobjectcleanuphandler.h \
		/home/wj/anaconda3/include/qt/QtCore/qoperatingsystemversion.h \
		/home/wj/anaconda3/include/qt/QtCore/qparallelanimationgroup.h \
		/home/wj/anaconda3/include/qt/QtCore/qpauseanimation.h \
		/home/wj/anaconda3/include/qt/QtCore/qplugin.h \
		/home/wj/anaconda3/include/qt/QtCore/qpointer.h \
		/home/wj/anaconda3/include/qt/QtCore/qpluginloader.h \
		/home/wj/anaconda3/include/qt/QtCore/qprocess.h \
		/home/wj/anaconda3/include/qt/QtCore/qpropertyanimation.h \
		/home/wj/anaconda3/include/qt/QtCore/qvariantanimation.h \
		/home/wj/anaconda3/include/qt/QtCore/qqueue.h \
		/home/wj/anaconda3/include/qt/QtCore/qreadwritelock.h \
		/home/wj/anaconda3/include/qt/QtCore/qrect.h \
		/home/wj/anaconda3/include/qt/QtCore/qsize.h \
		/home/wj/anaconda3/include/qt/QtCore/qregularexpression.h \
		/home/wj/anaconda3/include/qt/QtCore/qresource.h \
		/home/wj/anaconda3/include/qt/QtCore/qsavefile.h \
		/home/wj/anaconda3/include/qt/QtCore/qscopedvaluerollback.h \
		/home/wj/anaconda3/include/qt/QtCore/qsemaphore.h \
		/home/wj/anaconda3/include/qt/QtCore/qsequentialanimationgroup.h \
		/home/wj/anaconda3/include/qt/QtCore/qsettings.h \
		/home/wj/anaconda3/include/qt/QtCore/qsharedmemory.h \
		/home/wj/anaconda3/include/qt/QtCore/qsignalmapper.h \
		/home/wj/anaconda3/include/qt/QtCore/qsignaltransition.h \
		/home/wj/anaconda3/include/qt/QtCore/qsocketnotifier.h \
		/home/wj/anaconda3/include/qt/QtCore/qsortfilterproxymodel.h \
		/home/wj/anaconda3/include/qt/QtCore/qstack.h \
		/home/wj/anaconda3/include/qt/QtCore/qstandardpaths.h \
		/home/wj/anaconda3/include/qt/QtCore/qstate.h \
		/home/wj/anaconda3/include/qt/QtCore/qstatemachine.h \
		/home/wj/anaconda3/include/qt/QtCore/qstorageinfo.h \
		/home/wj/anaconda3/include/qt/QtCore/qstringlistmodel.h \
		/home/wj/anaconda3/include/qt/QtCore/qsystemsemaphore.h \
		/home/wj/anaconda3/include/qt/QtCore/qtemporarydir.h \
		/home/wj/anaconda3/include/qt/QtCore/QScopedPointer \
		/home/wj/anaconda3/include/qt/QtCore/qtemporaryfile.h \
		/home/wj/anaconda3/include/qt/QtCore/qtextboundaryfinder.h \
		/home/wj/anaconda3/include/qt/QtCore/qtextcodec.h \
		/home/wj/anaconda3/include/qt/QtCore/qthread.h \
		/home/wj/anaconda3/include/qt/QtCore/qthreadpool.h \
		/home/wj/anaconda3/include/qt/QtCore/qthreadstorage.h \
		/home/wj/anaconda3/include/qt/QtCore/qtimeline.h \
		/home/wj/anaconda3/include/qt/QtCore/qtimer.h \
		/home/wj/anaconda3/include/qt/QtCore/qtimezone.h \
		/home/wj/anaconda3/include/qt/QtCore/qtranslator.h \
		/home/wj/anaconda3/include/qt/QtCore/qtypetraits.h \
		/home/wj/anaconda3/include/qt/QtCore/qurl.h \
		/home/wj/anaconda3/include/qt/QtCore/qurlquery.h \
		/home/wj/anaconda3/include/qt/QtCore/quuid.h \
		/home/wj/anaconda3/include/qt/QtCore/qwaitcondition.h \
		/home/wj/anaconda3/include/qt/QtCore/qwineventnotifier.h \
		/home/wj/anaconda3/include/qt/QtCore/qxmlstream.h \
		/home/wj/anaconda3/include/qt/QtCore/qtcoreversion.h \
		/home/wj/anaconda3/include/qt/QtGui/QtGui \
		/home/wj/anaconda3/include/qt/QtGui/QtGuiDepends \
		/home/wj/anaconda3/include/qt/QtGui/qtguiglobal.h \
		/home/wj/anaconda3/include/qt/QtGui/qtgui-config.h \
		/home/wj/anaconda3/include/qt/QtGui/qabstracttextdocumentlayout.h \
		/home/wj/anaconda3/include/qt/QtGui/qtextlayout.h \
		/home/wj/anaconda3/include/qt/QtGui/qcolor.h \
		/home/wj/anaconda3/include/qt/QtGui/qrgb.h \
		/home/wj/anaconda3/include/qt/QtGui/qrgba64.h \
		/home/wj/anaconda3/include/qt/QtGui/qevent.h \
		/home/wj/anaconda3/include/qt/QtGui/qwindowdefs.h \
		/home/wj/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/home/wj/anaconda3/include/qt/QtGui/qregion.h \
		/home/wj/anaconda3/include/qt/QtGui/qkeysequence.h \
		/home/wj/anaconda3/include/qt/QtGui/qvector2d.h \
		/home/wj/anaconda3/include/qt/QtGui/qtouchdevice.h \
		/home/wj/anaconda3/include/qt/QtGui/qtextformat.h \
		/home/wj/anaconda3/include/qt/QtGui/qfont.h \
		/home/wj/anaconda3/include/qt/QtGui/qpen.h \
		/home/wj/anaconda3/include/qt/QtGui/qbrush.h \
		/home/wj/anaconda3/include/qt/QtGui/qmatrix.h \
		/home/wj/anaconda3/include/qt/QtGui/qpolygon.h \
		/home/wj/anaconda3/include/qt/QtGui/qtransform.h \
		/home/wj/anaconda3/include/qt/QtGui/qpainterpath.h \
		/home/wj/anaconda3/include/qt/QtGui/qimage.h \
		/home/wj/anaconda3/include/qt/QtGui/qpaintdevice.h \
		/home/wj/anaconda3/include/qt/QtGui/qpixelformat.h \
		/home/wj/anaconda3/include/qt/QtGui/qpixmap.h \
		/home/wj/anaconda3/include/qt/QtGui/qtextoption.h \
		/home/wj/anaconda3/include/qt/QtGui/qglyphrun.h \
		/home/wj/anaconda3/include/qt/QtGui/qrawfont.h \
		/home/wj/anaconda3/include/qt/QtGui/qfontdatabase.h \
		/home/wj/anaconda3/include/qt/QtGui/qtextcursor.h \
		/home/wj/anaconda3/include/qt/QtGui/qtextdocument.h \
		/home/wj/anaconda3/include/qt/QtGui/qpalette.h \
		/home/wj/anaconda3/include/qt/QtGui/qaccessible.h \
		/home/wj/anaconda3/include/qt/QtGui/qaccessiblebridge.h \
		/home/wj/anaconda3/include/qt/QtGui/qaccessibleobject.h \
		/home/wj/anaconda3/include/qt/QtGui/qaccessibleplugin.h \
		/home/wj/anaconda3/include/qt/QtGui/qbackingstore.h \
		/home/wj/anaconda3/include/qt/QtGui/qwindow.h \
		/home/wj/anaconda3/include/qt/QtCore/QEvent \
		/home/wj/anaconda3/include/qt/QtCore/QMargins \
		/home/wj/anaconda3/include/qt/QtCore/QRect \
		/home/wj/anaconda3/include/qt/QtGui/qsurface.h \
		/home/wj/anaconda3/include/qt/QtGui/qsurfaceformat.h \
		/home/wj/anaconda3/include/qt/QtGui/qicon.h \
		/home/wj/anaconda3/include/qt/QtGui/qcursor.h \
		/home/wj/anaconda3/include/qt/QtGui/qbitmap.h \
		/home/wj/anaconda3/include/qt/QtGui/qclipboard.h \
		/home/wj/anaconda3/include/qt/QtGui/qdesktopservices.h \
		/home/wj/anaconda3/include/qt/QtGui/qdrag.h \
		/home/wj/anaconda3/include/qt/QtGui/qfontinfo.h \
		/home/wj/anaconda3/include/qt/QtGui/qfontmetrics.h \
		/home/wj/anaconda3/include/qt/QtGui/qgenericmatrix.h \
		/home/wj/anaconda3/include/qt/QtGui/qgenericplugin.h \
		/home/wj/anaconda3/include/qt/QtGui/qgenericpluginfactory.h \
		/home/wj/anaconda3/include/qt/QtGui/qguiapplication.h \
		/home/wj/anaconda3/include/qt/QtGui/qinputmethod.h \
		/home/wj/anaconda3/include/qt/QtGui/qiconengine.h \
		/home/wj/anaconda3/include/qt/QtGui/qiconengineplugin.h \
		/home/wj/anaconda3/include/qt/QtGui/qimageiohandler.h \
		/home/wj/anaconda3/include/qt/QtGui/qimagereader.h \
		/home/wj/anaconda3/include/qt/QtGui/qimagewriter.h \
		/home/wj/anaconda3/include/qt/QtGui/qmatrix4x4.h \
		/home/wj/anaconda3/include/qt/QtGui/qvector3d.h \
		/home/wj/anaconda3/include/qt/QtGui/qvector4d.h \
		/home/wj/anaconda3/include/qt/QtGui/qquaternion.h \
		/home/wj/anaconda3/include/qt/QtGui/qmovie.h \
		/home/wj/anaconda3/include/qt/QtGui/qoffscreensurface.h \
		/home/wj/anaconda3/include/qt/QtGui/qopengl.h \
		/home/wj/anaconda3/include/qt/QtCore/qt_windows.h \
		/home/wj/anaconda3/include/qt/QtGui/qopengles2ext.h \
		/home/wj/anaconda3/include/qt/QtGui/qopenglext.h \
		/home/wj/anaconda3/include/qt/QtGui/qopenglbuffer.h \
		/home/wj/anaconda3/include/qt/QtGui/qopenglcontext.h \
		/home/wj/anaconda3/include/qt/QtGui/QSurfaceFormat \
		/home/wj/anaconda3/include/qt/QtGui/qopenglversionfunctions.h \
		/home/wj/anaconda3/include/qt/QtGui/qopengldebug.h \
		/home/wj/anaconda3/include/qt/QtGui/qopenglextrafunctions.h \
		/home/wj/anaconda3/include/qt/QtGui/qopenglfunctions.h \
		/home/wj/anaconda3/include/qt/QtGui/qopenglframebufferobject.h \
		/home/wj/anaconda3/include/qt/QtGui/qopenglpaintdevice.h \
		/home/wj/anaconda3/include/qt/QtGui/qopenglpixeltransferoptions.h \
		/home/wj/anaconda3/include/qt/QtCore/QSharedDataPointer \
		/home/wj/anaconda3/include/qt/QtGui/qopenglshaderprogram.h \
		/home/wj/anaconda3/include/qt/QtGui/qopengltexture.h \
		/home/wj/anaconda3/include/qt/QtGui/qopengltextureblitter.h \
		/home/wj/anaconda3/include/qt/QtGui/QMatrix3x3 \
		/home/wj/anaconda3/include/qt/QtGui/QMatrix4x4 \
		/home/wj/anaconda3/include/qt/QtGui/qopengltimerquery.h \
		/home/wj/anaconda3/include/qt/QtGui/qopenglvertexarrayobject.h \
		/home/wj/anaconda3/include/qt/QtGui/qopenglwindow.h \
		/home/wj/anaconda3/include/qt/QtGui/QPaintDeviceWindow \
		/home/wj/anaconda3/include/qt/QtGui/qpaintdevicewindow.h \
		/home/wj/anaconda3/include/qt/QtGui/QWindow \
		/home/wj/anaconda3/include/qt/QtGui/QPaintDevice \
		/home/wj/anaconda3/include/qt/QtGui/QOpenGLContext \
		/home/wj/anaconda3/include/qt/QtGui/QImage \
		/home/wj/anaconda3/include/qt/QtGui/qpagedpaintdevice.h \
		/home/wj/anaconda3/include/qt/QtGui/qpagelayout.h \
		/home/wj/anaconda3/include/qt/QtGui/qpagesize.h \
		/home/wj/anaconda3/include/qt/QtGui/qpaintengine.h \
		/home/wj/anaconda3/include/qt/QtGui/qpainter.h \
		/home/wj/anaconda3/include/qt/QtGui/qpdfwriter.h \
		/home/wj/anaconda3/include/qt/QtGui/qpicture.h \
		/home/wj/anaconda3/include/qt/QtGui/qpictureformatplugin.h \
		/home/wj/anaconda3/include/qt/QtGui/qpixmapcache.h \
		/home/wj/anaconda3/include/qt/QtGui/qrasterwindow.h \
		/home/wj/anaconda3/include/qt/QtGui/qscreen.h \
		/home/wj/anaconda3/include/qt/QtCore/QList \
		/home/wj/anaconda3/include/qt/QtCore/QSize \
		/home/wj/anaconda3/include/qt/QtCore/QSizeF \
		/home/wj/anaconda3/include/qt/QtGui/QTransform \
		/home/wj/anaconda3/include/qt/QtGui/qsessionmanager.h \
		/home/wj/anaconda3/include/qt/QtGui/qstandarditemmodel.h \
		/home/wj/anaconda3/include/qt/QtGui/qstatictext.h \
		/home/wj/anaconda3/include/qt/QtGui/qstylehints.h \
		/home/wj/anaconda3/include/qt/QtGui/qsyntaxhighlighter.h \
		/home/wj/anaconda3/include/qt/QtGui/qtextobject.h \
		/home/wj/anaconda3/include/qt/QtGui/qtextdocumentfragment.h \
		/home/wj/anaconda3/include/qt/QtGui/qtextdocumentwriter.h \
		/home/wj/anaconda3/include/qt/QtGui/qtextlist.h \
		/home/wj/anaconda3/include/qt/QtGui/qtexttable.h \
		/home/wj/anaconda3/include/qt/QtGui/qvalidator.h \
		/home/wj/anaconda3/include/qt/QtGui/qtguiversion.h \
		/home/wj/anaconda3/include/qt/QtWidgets/QApplication \
		/home/wj/anaconda3/include/qt/QtWidgets/qapplication.h \
		/home/wj/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/home/wj/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/home/wj/anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		/home/wj/anaconda3/include/qt/QtWidgets/qwidget.h \
		/home/wj/anaconda3/include/qt/QtWidgets/qsizepolicy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

